# Generated by Django 3.1.6 on 2021-02-17 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=48)),
                ('avatar', models.URLField()),
                ('birthday', models.CharField(max_length=10)),
                ('tagline', models.CharField(max_length=200)),
            ],
        ),
    ]
